'on':
  github:
    branches:
      only: main
jobs:
  GetApex:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: 'https://github.com/NVIDIA/apex.git'
  SetupApex:
    resources:
      instance-type: C5
    needs:
      - GetApex
    inputs:
      repo: GetApex.outputs.repo
    uses: script@v1
    with:
      script: python /inputs/repo/setup.py install --cuda_ext --cpp_ext
      image: tensorflow/tensorflow:1.14.0-py3
